channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::snakemake-minimal =5.4.5
  - python =3.7
  - bcftools =1.10.2-0
  - samtools =1.10
  - bwa =0.7.17
  - bedtools =2.29.2-0
  - graphviz =2.40.1
  - pigz =2.4
  - gatk4 =4.1.7.0-0
  - pandas =1.0.5
  - bioconda::fastqc =0.11.9
